### ISSUE TITLE
Recent error

### ISSUE THREAD

**Issue by fssem1** [pbs-assess/rosettafish#21]
A few months ago I used this code to access your package:
library("devtools")
devtools::install_github("pbs-assess/rosettafish")
library(rosettafish)
source('state_space_model/code/functions.r')

terms.use <- read.csv("state_space_model/data/translation_terms.csv",stringsAsFactors = FALSE)

rosettafish::trans("Overfishing Profile", from = "english", to = "french", 
                   custom_terms = terms.use, allow_missing = FALSE)

Now this function does not work and I am getting the error:
Error in xj[i] : only 0's may be mixed with negative subscripts
[translation_terms.txt](https://github.com/pbs-assess/rosettafish/files/4183621/translation_terms.txt)

I included a text version of my translations (I use a csv in the above code but it would not attach a csv file.)

Also, I tried to use your directions to change the terms. csv file for the package and did not have any luck.

**Comment by seananderson** [comment]
Try it now after [this](https://github.com/pbs-assess/rosettafish/commit/7527a730254125de3026e4f9ca36c0ac154d8038). That works for me.

**Comment by seananderson** [comment]
For editing, the easiest:

1.  [Edit the file directly on GitHub](https://github.com/pbs-assess/rosettafish/edit/master/data-raw/terms.csv).
2.  Add the terms to the end of the file.
3.  Click the button to create a pull request.

Or, [create an Issue](https://github.com/pbs-assess/rosettafish/issues/new) on the GitHub site and give us your new translated terms.

I would generally do the `a) ` etc. part using something like `paste0()` after to keep the dictionary more general.
